name: build emulation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - emulation/**
jobs:
  push:
    name: "yolks:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - box64
          - box86
          - emulation
          - box_proton
          - fex_proton
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./emulation/${{ matrix.tag }}
          file: ./emulation/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:${{ matrix.tag }}
