name: build temp
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - temp/**
jobs:
  # pushArm:
  #     name: "yolks:tempARM_${{ matrix.tag }}"
  #     runs-on: ubuntu-latest
  #     strategy:
  #       fail-fast: false
  #       matrix:
  #         tag:
  #     steps:
  #       - uses: actions/checkout@v4
  #       - uses: docker/setup-buildx-action@v3
  #         with:
  #           buildkitd-flags: --debug
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v2
  #         with:
  #           platforms: arm64,amd64
  #       - name: Cache Docker layers
  #         uses: actions/cache@v3
  #         with:
  #           path: /tmp/.buildx-cache
  #           key: ${{ runner.os }}-buildx-${{ github.sha }}
  #           restore-keys: |
  #             ${{ runner.os }}-buildx-
  #       - uses: docker/login-action@v3
  #         with:
  #           username: ${{ secrets.REPOSITORY_OWNER }}
  #           password: ${{ secrets.REGISTRY_TOKEN }}
  #       - uses: docker/build-push-action@v6
  #         with:
  #           context: ./temp/${{ matrix.tag }}
  #           file: ./temp/${{ matrix.tag }}/Dockerfile
  #           platforms: linux/arm64
  #           cache-from: type=local,src=/tmp/.buildx-cache
  #           cache-to: type=local,dest=/tmp/.buildx-cache-new
  #           push: true
  #           tags: |
  #              quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}

  # pushAll:
  #    name: "yolks:tempALL_${{ matrix.tag }}"
  #    runs-on: ubuntu-latest
  #    strategy:
  #      fail-fast: false
  #      matrix:
  #        tag:
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v2
  #        with:
  #          platforms: arm64,amd64
  #      - uses: docker/setup-buildx-action@v3
  #        with:
  #          buildkitd-flags: --debug
  #      - uses: docker/login-action@v3
  #        with:
  #          username: ${{ secrets.REPOSITORY_OWNER }}
  #          password: ${{ secrets.REGISTRY_TOKEN }}
  #      - uses: docker/build-push-action@v6
  #        with:
  #          context: ./temp/${{ matrix.tag }}
  #          file: ./temp/${{ matrix.tag }}/Dockerfile
  #          platforms: linux/amd64,linux/arm64
  #          push: true
  #          tags: |
  #            quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}
  pushAMD:
    name: "yolks:tempAMD_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - nodejs_18_puppeteer
          - pavlov_vr
          - rathena
          - "experimental"
          - "experimental_v2"
          - "java_21"   
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./temp/${{ matrix.tag }}
          file: ./temp/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}
