name: build wine
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - wine/**
jobs:
  push:
    name: "yolks:wine_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - stable
          - staging
          - '8'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./wine
          file: ./wine/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:wine_${{ matrix.tag }}
